FROM python:3.9.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV SECRET_KEY={SOLEFI_API_SECRET_KEY} \
    ENVT={SOLEFI_API_ENVIRONMENT} \
    DB_NAME={SOLEFI_API_POSTGRES_DB} \
    DB_USER={SOLEFI_API_POSTGRES_USER} \
    DB_PASSWORD={SOLEFI_API_POSTGRES_PASSWORD} \
    EMAIL_HOST_USER={SOLEFI_API_EMAIL_HOST_USER} \
    EMAIL_HOST_PASSWORD={SOLEFI_API_EMAIL_HOST_PASSWORD}

WORKDIR /app

COPY . .

RUN python3 -m pip install -r requirements.txt

CMD [ "/bin/sh", "docker-entrypoint.sh" ]
