FROM python:3.9.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG SECRET_KEY
ARG ENVIRONMENT
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD
ARG PUBLIC_PORT

WORKDIR /app

COPY . .

RUN python3 -m pip install -r requirements.txt

CMD [ "/bin/sh", "docker-entrypoint.sh" ]
