# Generated by Django 3.0.6 on 2021-05-06 05:34

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import pages.models.page
import pages.models.seo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('main_phone', models.CharField(blank=True, max_length=10, null=True, validators=[common.validators.ModelValidators.phone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('keywords', models.CharField(blank=True, max_length=64, null=True)),
                ('og_type', models.CharField(choices=[('Web Page', 'Web Page'), ('Article', 'Article')], default='Web Page', max_length=32)),
                ('og_title', models.CharField(blank=True, max_length=64, null=True)),
                ('og_site_name', models.CharField(blank=True, max_length=64, null=True)),
                ('og_description', models.CharField(blank=True, max_length=128, null=True)),
                ('img_og_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[512, 512], upload_to=pages.models.seo.picture)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('dns', models.URLField()),
                ('slogan', models.CharField(blank=True, max_length=128, null=True)),
                ('img_logo', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=95, size=[256, 256], upload_to=pages.models.page.logo)),
                ('views', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=32)),
                ('receptor_name', models.CharField(blank=True, max_length=64, null=True, validators=[common.validators.ModelValidators.name])),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[common.validators.ModelValidators.phone])),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, validators=[common.validators.ModelValidators.zip_code])),
                ('street', models.CharField(max_length=32)),
                ('ext_number', models.CharField(blank=True, max_length=5, null=True)),
                ('int_number', models.CharField(blank=True, max_length=5, null=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_address_city', to='common.City')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_main_address', to='pages.PageAddress'),
        ),
        migrations.AddField(
            model_name='page',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='page_branches_address', to='pages.PageAddress'),
        ),
    ]
