# Generated by Django 3.0.6 on 2021-05-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210508_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
