# Generated by Django 3.0.6 on 2021-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pageaddress_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='og_description',
            field=models.CharField(default='Page description', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='og_site_name',
            field=models.CharField(default='Web page', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='og_title',
            field=models.CharField(default='Web page', max_length=64),
            preserve_default=False,
        ),
    ]
