# Generated by Django 3.0.6 on 2021-07-16 07:14

from django.db import migrations
import django_resized.forms
import pages.models.page


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210528_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img_logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[512, 512], upload_to=pages.models.page.logo),
        ),
    ]
