# Generated by Django 3.0.6 on 2021-07-16 07:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210716_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='platform_description',
            field=tinymce.models.HTMLField(default='Todo lo que necesitas para tu empresa en un sólo lugar.'),
        ),
        migrations.AddField(
            model_name='page',
            name='platform_link',
            field=models.URLField(default='https://www.listo.mx/entrar'),
        ),
        migrations.AddField(
            model_name='page',
            name='platform_promo_link',
            field=models.URLField(default='https://listo.mx/registro?cobranding_id=6'),
        ),
        migrations.AddField(
            model_name='page',
            name='platform_title',
            field=models.CharField(default='Plataforma', max_length=32),
        ),
    ]
