# Generated by Django 3.0.6 on 2021-07-16 07:30

from django.db import migrations
import django_resized.forms
import pages.models.page


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210716_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='img_platform',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=93, size=[1024, 1024], upload_to=pages.models.page.logo),
        ),
    ]
