# Generated by Django 3.0.6 on 2021-05-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_grid', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogriditem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_infoGrid_item', to='pages.Page'),
        ),
        migrations.AddField(
            model_name='infogrid',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_of_infoGrid', to='info_grid.InfoGridItem'),
        ),
        migrations.AddField(
            model_name='infogrid',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_info_grid', to='pages.Page'),
        ),
    ]
