# Generated by Django 3.0.6 on 2021-05-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_grid', '0002_auto_20210506_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infogriditem',
            old_name='name',
            new_name='title',
        ),
    ]
