# Generated by Django 3.0.6 on 2021-05-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_grid', '0003_auto_20210506_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogrid',
            name='name',
            field=models.SlugField(default='my-slug', max_length=32),
            preserve_default=False,
        ),
    ]
