# Generated by Django 3.0.6 on 2021-05-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_grid', '0006_infogrid_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogrid',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
