# Generated by Django 3.0.6 on 2021-05-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210528_0607'),
        ('info_grid', '0008_infogriditem_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogrid',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_info_grid', to='pages.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infogriditem',
            name='info_grid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info_grid_item', to='info_grid.InfoGrid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infogriditem',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_infoGrid_item', to='pages.Page'),
            preserve_default=False,
        ),
    ]
