# Generated by Django 3.0.6 on 2021-07-17 04:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_grid', '0009_auto_20210528_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogriditem',
            name='secondary_color',
            field=colorfield.fields.ColorField(blank=True, default='#42a5f5', max_length=18, null=True),
        ),
    ]
