# Generated by Django 3.0.6 on 2021-07-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_grid', '0010_infogriditem_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogriditem',
            name='gradient_degree',
            field=models.PositiveIntegerField(blank=True, default=45, null=True),
        ),
    ]
