# Generated by Django 3.0.6 on 2021-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_grid', '0014_auto_20210717_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogriditem',
            name='image_position',
            field=models.CharField(blank=True, choices=[('top', 'top'), ('bottom', 'bottom'), ('left', 'left'), ('right', 'right')], default='left', max_length=32, null=True),
        ),
    ]
