# Generated by Django 3.2.12 on 2022-03-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_grid', '0015_auto_20210717_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogrid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='infogriditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
